### ISSUE TITLE
http-mock/http-proxy

### ISSUE THREAD

**Issue by chrisvdp** [kimroen/ember-cli-coffeescript#14]
Is there a reason that there are no http-mock/http-proxy blueprints or are they just not implemented yet?

**Comment by ohcibi** [comment]
It is possible to use coffee-script mocks as follows:

* require `coffee-script/register/` in your server module (ember-cli puts it in `server/index.js`)
* require `*.coffee` files instead of js

```js
module.exports = function(app) {
  require('coffee-script/register');

  var globSync   = require('glob').sync;
  var mocks      = globSync('./mocks/**/*.coffee', { cwd: __dirname }).map(require);
  // .....
```

In any node.js app you just require the coffee-script/register module and from there on you can require any coffee-scripted module.
